package(default_visibility = ["//visibility:public"])

py_library(
    name = "function_call",
    srcs = ["function_executor.py"],
    deps = [
        "//llm_scheduler/config_schema",
        "//llm_scheduler/executor:executor",
        "//llm_scheduler/executor/function_call/logging",
    ],
)
